# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_arbitro', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=70)),
                ('escudo', models.CharField(max_length=70)),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=70)),
                ('posicion', models.CharField(max_length=70)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga_asobal.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.IntegerField()),
                ('goles_visitante', models.IntegerField()),
                ('fecha_partido', models.DateTimeField(verbose_name='date published')),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga_asobal.Arbitro')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local', to='liga_asobal.Equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visitante', to='liga_asobal.Equipo')),
            ],
        ),
    ]
