# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga_asobal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
